name: CI/CD Pipeline for Spring Boot

on:
  push:
    branches:
      - master

jobs:
  Build_and_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}-
      - name: Install Dependencies & Build
        run: mvn clean install -DskipTests
      - name: Run Tests
        run: mvn test

  Build_Docker_Image:
    needs: Build_and_Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker Image
        run: docker build -t samruddhig/ecomproject .
      - name: Push Image to Docker Hub
        run: docker push samruddhig/ecomproject:latest

  Deploy_to_Production:
    needs: Build_Docker_Image
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image from Hub
        run: docker pull samruddhig/ecomproject:latest
      - name: Remove Old Container
        run: docker rm -f spring-boot-container || true
      - name: Run Docker Container
        run: docker run -d -p 8080:8080 --name spring-boot-container samruddhig/ecomproject

